applications/reinventor/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

from applications.reinventor.api.api import WithdrawalRequestUpdateAPIView, generatePdfAPIView
from applications.reinventor.views_error import error404
from . import views, views_ajax

app_name = 'reinventa_app'

urlpatterns = [
    path('dashboard/', views.controlPanel, name='panel-control'),
    path('listado-reinventores/', views.verReinventores, name='ver-reinventores'),
    path('crear-reinventor/', views.addReinventor, name='add-reinventor'),
    path('editar-reinventor/<int:re_id>', views.editReinventor, name='edit-reinventor'),
    path('borrar-reinventor/<int:re_id>', views.deleteReinventor, name='delete-reinventor'),
    path('logo-reinventor/<int:re_id>', views.addLogoReinventor, name='logo-reinventor'),

    path('configuracion', views.configurationCompany, name='configuracion'),

    path('crear-configuracion/', views.addConfiguration, name='crear-configuracion'),
    path('edit-configuracion/<int:co_id>', views.editConfiguration, name='edit-configuracion'),


    path('ver-request/', views.viewRequestAdmin, name='ver-request'),
    path('ver-user/', views.viewUserAdmin, name='ver-user'),
    path('add-user/', views.addUserAdmin, name='add-user'),
    path('edit-user/<int:id>', views.editUserAdmin, name='edit-user'),


    path('add-user-reinventor/<int:re_id>', views.addUserReinventor, name='add-user-reinventor'),
    path('edit-user-reinventor/<int:re_id>/<int:id>', views.editUserReinventor, name='edit-user-reinventor'),
    path('delete-user-reinventor/<int:re_id>/<int:id>', views.deleteUserReinventor, name='delete-user-reinventor'),


    path('list-request-reinventor/', views.listRequestReinventor, name='list-request-reinventor'),
    path('crear-request-reinventor/', views.addRequestReinventor, name='crear-request-reinventor'),
    path('edit-request-reinventor/<int:wrr_id>', views.editRequestReinventor, name='edit-request-reinventor'),
    path('ver-request-reinventor-adm/<int:wrr_id>', views.editRequestReinventor, name='edit-request-reinventor-adm'),


    path('add-observations/<int:wrr_id>', views.addObservations, name='add-observations'),
    path('edit-observations/<int:wrr_id>/<int:rt_id>', views.editObservations, name='edit-observations'),



    #ajax
    path('ajax/nueva-observacion/', views_ajax.new_observation, name='new_observation'),
    path('ajax/upload-file/', views_ajax.upload_file, name='upload_file'),
    path('ajax/download-excel-for-upload-reinventor/', views_ajax.download_excel_for_upload_reinventor, name='download_excel_for_upload_reinventor'),


    #api
    path('api/actualizar-estado/', WithdrawalRequestUpdateAPIView.as_view(), name='actualizar_estado'),
    path('api/generar-pdf/', generatePdfAPIView.as_view(), name='generar_pdf'),


    path('error404/', error404, name='error404'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reinventa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenBlacklistView
)

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from applications.account.api.api import Login, Logout
from applications.account.views import logout, logout_view

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version='v1',
        description="API documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@yourcompany.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[],
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('login/', Login.as_view(), name='login'),
    #path('logout/', Logout.as_view(), name='logout'),
    path('logout/', logout_view, name='logout'),

    path('', include('applications.account.urls')),
    path('', include('applications.reinventor.urls')),
    path('', include('applications.web.urls')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/blacklist/', TokenBlacklistView.as_view(), name='token_blacklist'),
]

applications/account/models.py
from django.contrib.auth.models import User
from django.db import models
from model_utils.models import TimeStampedModel


# Create your models here.

class Pais(TimeStampedModel):
    pa_id = models.AutoField("Key", primary_key=True)
    pa_nombre = models.CharField("Nombre país", max_length=255)
    pa_codigo = models.IntegerField("Código area país", unique=True)

    def __int__(self):
        return self.pa_id

    def __str__(self):
        return "{n}".format(n=self.pa_nombre.title())

    def save(self, *args, **kwargs):
        # print "save cto"
        super(Pais, self).save(*args, **kwargs)

    class Meta:
        db_table = 'conf_pais'
        ordering = ['pa_id']


class Region(TimeStampedModel):
    re_id = models.AutoField("Key", primary_key=True)
    re_nombre = models.CharField("Nombre región", max_length=255)
    pais = models.ForeignKey(Pais, verbose_name="País", blank=True, null=True, on_delete=models.PROTECT,
                             db_column="re_pais")
    re_numeroregion = models.CharField(
        "Sigla de región", blank=True, null=True, max_length=5)
    re_numero = models.IntegerField("Número de región", db_index=True)

    def __int__(self):
        return self.re_id

    def __str__(self):
        return "{n}".format(n=self.re_nombre.title())

    def save(self, *args, **kwargs):
        # print "save cto"
        super(Region, self).save(*args, **kwargs)

    class Meta:
        db_table = 'conf_region'
        ordering = ['re_id']


class Comuna(TimeStampedModel):
    com_id = models.AutoField("Key", primary_key=True)
    com_nombre = models.CharField("Nombre comuna", max_length=255)
    com_numero = models.IntegerField("Numero comuna", default=0)
    region = models.ForeignKey(Region, verbose_name="Región", blank=True, null=True, on_delete=models.PROTECT,
                               db_column="com_region")

    def __int__(self):
        return self.com_id

    def __str__(self):
        return "{n}".format(n=self.com_nombre.title())

    def save(self, *args, **kwargs):
        # print "save cto"
        super(Comuna, self).save(*args, **kwargs)

    class Meta:
        db_table = 'conf_comuna'
        ordering = ['com_id']


class Reinventor(TimeStampedModel): 

    OPTIONS = (
        ('Y', 'SI'),
        ('N', 'NO'),
    )

    re_id = models.AutoField("Key", primary_key=True)
    re_nameentity = models.CharField("Nombre empresa", max_length=255)
    # re_email = models.CharField("Correo empresa", max_length=255, unique=True)
    re_email = models.EmailField("Correo empresa", max_length=255, null=True, blank=True)
    re_namereinventor = models.CharField("Nombre completo persona a cargo", max_length=255)
    re_address = models.CharField("Dirección de la empresa", help_text="ej: calle siempre viva 1010", max_length=255)
    pais = models.ForeignKey(Pais, verbose_name="País",
                             db_column="re_pais_id", on_delete=models.PROTECT)
    region = models.ForeignKey(
        Region, verbose_name="Región", db_column="re_region_id", on_delete=models.PROTECT)
    comuna = models.ForeignKey(
        Comuna, verbose_name="Comuna", db_column="re_comuna_id", on_delete=models.PROTECT)
    
    re_latitude = models.CharField("Latitud", max_length=255, null=True, blank=True)
    re_longitude = models.CharField("Longitud", max_length=255, null=True, blank=True)
    re_logo = models.ImageField(
        "Logo Empresa", help_text=" Formatos .jpg|.png|.gif|.jpeg", upload_to='image/logo/', null=True, blank=True)
    
    re_active = models.CharField(
        "Activo", choices=OPTIONS, max_length=1, default="Y")
    

    def __int__(self):
        return self.re_id
    
    def __str__(self):
        return f"{self.re_id} - {self.re_nameentity}"
    
    def __create_address(self):
        return f"""{ self.re_address }, { self.comuna.com_nombre }, { self.region.re_nombre }, { self.pais.pa_nombre }"""

    re_createaddress = property(__create_address)

    def save(self, *args, **kwargs):
        super(Reinventor, self).save(*args, **kwargs)

    class Meta:
        db_table = "re_reinventor"
        ordering = ['re_id']


class UserReinventor(TimeStampedModel):
    OPTIONS = (
        ('Y', 'SI'),
        ('N', 'NO'),
    )

    TYPE_USER = (
        (0, ' [Seleccione] '),
        (1, 'ADMINISTRADOR REINVENTA'),
        (2, 'REINVENTOR'),
    )

    ur_id = models.AutoField("Key", primary_key=True)
    user = models.ForeignKey(User, verbose_name="User",
                             db_column="ur_user_id", on_delete=models.PROTECT)
    reinventor = models.ForeignKey(Reinventor, verbose_name="Reinventor",
                             db_column="ur_reinventor_id", on_delete=models.PROTECT)
    ur_typeuser = models.IntegerField(
        "Tipo de usuario", choices=TYPE_USER, default=0)
    ur_logo = models.ImageField(
        "Imagen usuario", help_text=" Formatos .jpg|.png|.gif|.jpeg", upload_to='image/logo/', default='../media/site/user_default.png', null=True, blank=True)
    ur_active = models.CharField(
        "Activo", choices=OPTIONS, max_length=1, default="Y")

    def __int__(self):
        return self.ur_id
    
    def __str__(self):
        return f"{ self.ur_id } - { self.user.username }"

    def save(self, *args, **kwargs):
        super(UserReinventor, self).save(*args, **kwargs)

    class Meta:
        db_table = "re_user_reinventor"
        ordering = ['ur_id']


class WithdrawalRequestReinventor(TimeStampedModel):
    OPTIONS = (
        ('Y', 'SI'),
        ('N', 'NO'),
    )

    ESTATE_REQUEST = (
        (0, ' [Seleccione] '),
        (1, 'REINVENTOR SOLICITA'),
        (2, 'VISTA POR REINVENTA'),
        (3, 'REINVENTA VA EN RUTA'),
        (4, 'RETIRADO POR REINVENTA'),
    )

    wrr_id = models.AutoField("Key", primary_key=True)
    user = models.ForeignKey(User, verbose_name="User",
                             db_column="ur_user_id", on_delete=models.PROTECT)
    reinventor = models.ForeignKey(Reinventor, verbose_name="Reinventor",
                             db_column="ur_reinventor_id", on_delete=models.PROTECT)
    wrr_date = models.CharField("Fecha de retiro", null=True, blank=True, max_length=30)
    wrr_quantityliters = models.FloatField("Litros de aceite", null=True, blank=True)
    wrr_estaterequest = models.IntegerField(
        "Estado de la solicitud", choices=ESTATE_REQUEST, default=1, null=True, blank=True)
    wrr_active = models.CharField(
        "Activo", max_length=1, choices=OPTIONS, default="Y")

    def __int__(self):
        return self.wrr_id
    
    def __str__(self):
        return f"{ self.wrr_id } - { self.user.username } - { self.reinventor.re_nameentity }"

    def save(self, *args, **kwargs):
        super(WithdrawalRequestReinventor, self).save(*args, **kwargs)

    class Meta:
        db_table = "re_withdrawal_request_reinventor"
        ordering = ['wrr_id']


class RequestTracking(TimeStampedModel):

    rt_id = models.AutoField("Key", primary_key=True)
    user = models.ForeignKey(User, verbose_name="User",
                             db_column="rt_user_id", on_delete=models.PROTECT)
    withdrawalRequestReinventor = models.ForeignKey(WithdrawalRequestReinventor, verbose_name="WithdrawalRequestReinventor",
                             db_column="rt_withdrawal_request_reinventor", on_delete=models.PROTECT)
    
    rt_estaterequest = models.CharField("Estado de la solicitud", max_length=50, blank=True, null=True)
    
    rt_observation = models.TextField("Observación", null=True, blank=True)

    def __int__(self):
        return self.rt_id
    
    def __str__(self):
        return f"{ self.rt_id } - { self.user.username } - { self.rt_estaterequest }"

    def save(self, *args, **kwargs):
        super(RequestTracking, self).save(*args, **kwargs)

    class Meta:
        db_table = "re_request_tracking"
        ordering = ['rt_id']

applications/reinventor/models.py
from django.contrib.auth.models import User
from django.db import models
from model_utils.models import TimeStampedModel

from applications.account.models import Comuna, Pais, Region


# Create your models here.

class Company(TimeStampedModel):

    OPTIONS = (
        ('Y', 'SI'),
        ('N', 'NO'),
    )

    co_id = models.AutoField("Key", primary_key=True)
    co_name = models.CharField("Nombre Empresa", max_length=255)
    co_address = models.CharField("Dirección de la empresa", help_text="ej: calle siempre viva 1010", max_length=255)
    pais = models.ForeignKey(Pais, verbose_name="País",
                                    db_column="co_pais_id", on_delete=models.PROTECT)
    region = models.ForeignKey(
        Region, verbose_name="Región", db_column="co_region_id", on_delete=models.PROTECT)
    comuna = models.ForeignKey(
        Comuna, verbose_name="Comuna", db_column="co_comuna_id", on_delete=models.PROTECT)
    
    co_latitude = models.CharField("Latitud", max_length=255, null=True, blank=True)
    co_longitude = models.CharField("Longitud", max_length=255, null=True, blank=True)
    co_logo = models.ImageField(
        "Logo Empresa", help_text=" Formatos .jpg|.png|.gif|.jpeg", upload_to='image/logo/', null=True, blank=True)
    
    co_active = models.CharField(
        "Activo", choices=OPTIONS, max_length=1, default="Y")

    def __int__(self):
        return self.co_id

    def __str__(self):
        return f"{ self.co_id } - { self.co_name }"

    def save(self, *args, **kwargs):
        # print "save cto"
        super(Company, self).save(*args, **kwargs)

    class Meta:
        db_table = 'com_company'
        ordering = ['co_id']

templates/reinventor/pages/error404.html
{% extends 'administrator/base.html' %}

{% load static_tags %}
{% load static %}

{% block title %}Error 404{% endblock %}

{% block static_up %}

{% endblock %}

{% block title_page %}Error 404{% endblock %}

{% block sub_title_page %}
Error 404
{% endblock %}

{% block menu_action %}

{% endblock %}

{% block content_page %}
<div class="alert alert-danger" role="alert">
    <strong class="d-block d-sm-inline-block-force"><span class="fa fa-close"></span> Error 404: </strong> {{ message }}.
</div>
{% endblock %}

{% block static_down %}



{% endblock %}

templates/reinventor/pages/list_request_reinventor.html
{% extends 'administrator/base.html' %}

{% load static_tags %}
{% load static %}

{% block title %}Listado Reinventores{% endblock %}

{% block static_up %}
<!-- Datatables -->

<link href="{% statics_tag 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}"
    rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">


{% endblock %}

{% block title_page %}{% endblock %}

{% block sub_title_page %}
Listado de Solicitudes
{% endblock %}

{% block menu_action %}

{% endblock %}

{% block content_page %}
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Reinventa / Solicitudes</h3>
        </div>
        <div class="title_right">
            <div class="col-md-5 col-sm-5 form-group pull-right top_search">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <button type="button" class="btn btn-info btn-sm" onclick="redirectToUrl('{% url 'reinventa_app:crear-request-reinventor' %}')">Nueva solicitud <i class="fa fa-plus-circle"></i></button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><i class="fa fa-list-ul"></i> <small>Listado de solicitudes</small></h2>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable" class="table table-striped table-bordered datatable" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Usuario</th>
                                <th>Fecha del retiro</th>
                                <th>Listros de aceite</th>
                                <th>Estado de la solicitud</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in objects %}
                            <tr>
                                <td>{{ object.wrr_id }}</td>
                                <td>{{ object.user.first_name | upper }} {{ object.user.last_name | upper }}</td>
                                <td>{{ object.wrr_date }}</td>
                                <td>{{ object.wrr_quantityliters }}</td>
                                <td>{{ object.get_wrr_estaterequest_display }}</td>
                                <td>
                                    <button type="button" class="btn btn-info btn-sm" onclick="redirectToUrl('{% url 'reinventa_app:edit-request-reinventor' object.wrr_id %}')">Ver Solicitud <i class="fa fa-eye"></i></button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    
                    
                    <script>
                        const redirectToUrl = (url) => {
                            location.href = url;
                        }
                    
                        const deleteClient = (url) => {
                            $.confirm({
                                title: 'Confirmación',
                                content: 'Esta eguro de eliminar al reinventor?, para eliminar haga clic confirmar, de lo contrario cancelar',
                                buttons: {
                                    confirmar: function () {
                                        location.href = url;
                                    },
                                    cancelar: function () {
                                        $.alert('Operación cancelada');
                                    },
                                }
                            });
                        }
                    
                        
                    </script>
                
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block static_down %}
<!-- Datatables -->
<script src="{% statics_tag 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
<script src="{% statics_tag 'vendors/jszip/dist/jszip.min.js' %}"></script>
<script src="{% statics_tag 'vendors/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% statics_tag 'vendors/pdfmake/build/vfs_fonts.js' %}"></script>


{% endblock %}