applications/account/urls.py
from django.urls import path
from . import views

app_name = 'account_app'

urlpatterns = [
    path('inicia-sesion/', views.userLogin, name='login'),
    path('cerrar-sesion/', views.logout, name='cerrar-sesion'),
]

applications/reinventor/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

from applications.reinventor.api.api import WithdrawalRequestUpdateAPIView, generatePdfAPIView
from applications.reinventor.views_error import error404
from . import views, views_ajax

app_name = 'reinventa_app'

urlpatterns = [
    path('dashboard/', views.controlPanel, name='panel-control'),
    path('listado-reinventores/', views.verReinventores, name='ver-reinventores'),
    path('crear-reinventor/', views.addReinventor, name='add-reinventor'),
    path('editar-reinventor/<int:re_id>', views.editReinventor, name='edit-reinventor'),
    path('borrar-reinventor/<int:re_id>', views.deleteReinventor, name='delete-reinventor'),
    path('logo-reinventor/<int:re_id>', views.addLogoReinventor, name='logo-reinventor'),

    path('configuracion', views.configurationCompany, name='configuracion'),

    path('crear-configuracion/', views.addConfiguration, name='crear-configuracion'),
    path('edit-configuracion/<int:co_id>', views.editConfiguration, name='edit-configuracion'),


    path('ver-request/', views.viewRequestAdmin, name='ver-request'),
    path('ver-user/', views.viewUserAdmin, name='ver-user'),
    path('add-user/', views.addUserAdmin, name='add-user'),
    path('edit-user/<int:id>', views.editUserAdmin, name='edit-user'),


    path('add-user-reinventor/<int:re_id>', views.addUserReinventor, name='add-user-reinventor'),
    path('edit-user-reinventor/<int:re_id>/<int:id>', views.editUserReinventor, name='edit-user-reinventor'),
    path('delete-user-reinventor/<int:re_id>/<int:id>', views.deleteUserReinventor, name='delete-user-reinventor'),


    path('list-request-reinventor/', views.listRequestReinventor, name='list-request-reinventor'),
    path('crear-request-reinventor/', views.addRequestReinventor, name='crear-request-reinventor'),
    path('edit-request-reinventor/<int:wrr_id>', views.editRequestReinventor, name='edit-request-reinventor'),
    path('ver-request-reinventor-adm/<int:wrr_id>', views.editRequestReinventor, name='edit-request-reinventor-adm'),


    path('add-observations/<int:wrr_id>', views.addObservations, name='add-observations'),
    path('edit-observations/<int:wrr_id>/<int:rt_id>', views.editObservations, name='edit-observations'),



    #ajax
    path('ajax/nueva-observacion/', views_ajax.new_observation, name='new_observation'),
    path('ajax/upload-file/', views_ajax.upload_file, name='upload_file'),
    path('ajax/download-excel-for-upload-reinventor/', views_ajax.download_excel_for_upload_reinventor, name='download_excel_for_upload_reinventor'),


    #api
    path('api/actualizar-estado/', WithdrawalRequestUpdateAPIView.as_view(), name='actualizar_estado'),
    path('api/generar-pdf/', generatePdfAPIView.as_view(), name='generar_pdf'),


    path('error404/', error404, name='error404'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reinventa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenBlacklistView
)

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from applications.account.api.api import Login, Logout
from applications.account.views import logout, logout_view

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version='v1',
        description="API documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@yourcompany.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[],
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('login/', Login.as_view(), name='login'),
    #path('logout/', Logout.as_view(), name='logout'),
    path('logout/', logout_view, name='logout'),

    path('', include('applications.account.urls')),
    path('', include('applications.reinventor.urls')),
    path('', include('applications.web.urls')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/blacklist/', TokenBlacklistView.as_view(), name='token_blacklist'),
]

applications/reinventor/models.py
from django.contrib.auth.models import User
from django.db import models
from model_utils.models import TimeStampedModel

from applications.account.models import Comuna, Pais, Region


# Create your models here.

class Company(TimeStampedModel):

    OPTIONS = (
        ('Y', 'SI'),
        ('N', 'NO'),
    )

    co_id = models.AutoField("Key", primary_key=True)
    co_name = models.CharField("Nombre Empresa", max_length=255)
    co_address = models.CharField("Dirección de la empresa", help_text="ej: calle siempre viva 1010", max_length=255)
    pais = models.ForeignKey(Pais, verbose_name="País",
                                    db_column="co_pais_id", on_delete=models.PROTECT)
    region = models.ForeignKey(
        Region, verbose_name="Región", db_column="co_region_id", on_delete=models.PROTECT)
    comuna = models.ForeignKey(
        Comuna, verbose_name="Comuna", db_column="co_comuna_id", on_delete=models.PROTECT)
    
    co_latitude = models.CharField("Latitud", max_length=255, null=True, blank=True)
    co_longitude = models.CharField("Longitud", max_length=255, null=True, blank=True)
    co_logo = models.ImageField(
        "Logo Empresa", help_text=" Formatos .jpg|.png|.gif|.jpeg", upload_to='image/logo/', null=True, blank=True)
    
    co_active = models.CharField(
        "Activo", choices=OPTIONS, max_length=1, default="Y")

    def __int__(self):
        return self.co_id

    def __str__(self):
        return f"{ self.co_id } - { self.co_name }"

    def save(self, *args, **kwargs):
        # print "save cto"
        super(Company, self).save(*args, **kwargs)

    class Meta:
        db_table = 'com_company'
        ordering = ['co_id']

applications/reinventor/views.py
from decouple import config

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

from django.urls import reverse
from django.contrib.auth.hashers import make_password

from applications.account.models import Comuna, Pais, Region, Reinventor, RequestTracking, UserReinventor, WithdrawalRequestReinventor
from applications.reinventor.decorators import is_data
from applications.reinventor.forms import CompanyForm, ReinventorForm, ReinventorLogoForm, RequestTrackingForm, UserForm, WithdrawalRequestReinventorForm
from applications.reinventor.models import Company
from reinventa.Email import EmailSender
from reinventa.utils import getLatitudeLongitude

# Create your views here.

@login_required
@is_data
def viewRequestAdmin(request):
    objectsWithdrawalRequestReinventor = WithdrawalRequestReinventor.objects.filter(wrr_active = "Y")
    data = {
        'objectData': objectsWithdrawalRequestReinventor,
    }
    return render(request, 'administrator/pages/ver_request.html', data)


@login_required
def addUserAdmin(request):

    if request.method == 'POST':
        form = UserForm(request.POST)
        
        if form.is_valid():
            # Guardar los datos del formulario UserForm
            frm = form.save(commit=False)
            frm.is_staff = False
            frm.is_superuser = False
            frm.set_password(request.POST['password'])
            frm.save()

            ur = UserReinventor()
            ur.user = frm
            ur.ur_typeuser = 1
            ur.save()

            messages.success(request, 'Usuario creado exitosamente!.')
            return redirect('reinventa_app:edit-user', id=frm.id)
        
        else:
            for field in form:
                for error in field.errors:
                    messages.error(request, f"{field.label}: {error}")
    else:
        form = UserForm()
    data = {
        'action': 'crear',
        'form': form
    }
    return render(request, 'administrator/pages/form_users.html', data)


@login_required
def editUserAdmin(request, id):
    object = get_object_or_404(User, id=id)

    if request.method == 'POST':
        form = UserForm(request.POST, instance=object)
        if form.is_valid():
            frm = form.save(commit=False)

            if len(request.POST['password']) == 0:
                password = object.username
                hashed_password = make_password(password)
                frm.password = hashed_password
                frm.save()
            else:
                frm.set_password(request.POST['password'])
                frm.save()

            # Agregar mensaje de éxito
            messages.success(request, 'Usuario editado exitosamente.')
        else:
            for field in form:
                for error in field.errors:
                    messages.error(request, f"{field.label}: {error}")
    else:
        form = UserForm(instance=object)
    
    data = {
        'form': form,
        'action': 'editar',
        'id': id,
    }
    return render(request, 'administrator/pages/form_users.html', data)


@login_required
@is_data
def viewUserAdmin(request):
    objectsUserReinventor = UserReinventor.objects.filter(ur_active = "Y", ur_typeuser = 1)

    data = {
        'objectData': objectsUserReinventor,
    }
    return render(request, 'administrator/pages/ver_users.html', data)


@login_required
def configurationCompany(request):

    objCompany = (Company.objects.all()).first()

    if objCompany:
        form = CompanyForm(instance=objCompany)
        acction = 'editar'
        co_id = objCompany.co_id
        logo = objCompany.co_logo if objCompany.co_logo else "../media/site/default_image.jpg"
        try:
            request.session['logo_company'] = logo.url
        except:
            request.session['logo_company'] = ""
    else:
        form = CompanyForm()
        acction = 'crear'
        co_id = False
        logo = "../media/site/default_image.jpg"

    data = {
        'form': form,
        'acction': acction,
        'co_id': co_id,
        'logo': logo
    }
    return render(request, 'administrator/pages/form_company.html', data)


@login_required
def addConfiguration(request):

    if request.method == 'POST':
        form = CompanyForm(request.POST, request.FILES)
        
        if form.is_valid():
            # Guardar los datos del formulario UserForm
            frm = form.save(commit=False)
            frm.pais = Pais.objects.get(pa_id = request.POST['pais'])
            frm.region = Region.objects.get(re_id = request.POST['region'])
            frm.comuna = Comuna.objects.get(com_id = request.POST['comuna'])
            

            address = f"{ frm.co_address }, { frm.comuna.com_nombre }, { frm.region.re_nombre }, { frm.pais.pa_nombre }"
            lat_lng = getLatitudeLongitude(address)

            frm.save()

            msg = ""
            if not lat_lng:
                msg = "La ubicación no pudo ser detectada, ingrese la latitud y longitud manualmente"
            else:
                frm.co_latitude = lat_lng['latitude']
                frm.co_longitude = lat_lng['longitude']
                frm.save()

            
            messages.success(request, f'Configuración creada exitosamente!. {msg}')
            return redirect('reinventa_app:configuracion')
        
        else:
            for field in form:
                for error in field.errors:
                    messages.error(request, f"{field.label}: {error}")
            return redirect('reinventa_app:configuracion')
    else:
        return redirect('reinventa_app:configuracion')

@login_required
def editConfiguration(request, co_id):
    object = get_object_or_404(Company, co_id=co_id)

    if request.method == 'POST':
        form = CompanyForm(request.POST, request.FILES, instance=object)
        if form.is_valid():
            # Guardar los datos del formulario UserForm
            frm = form.save(commit=False)
            frm.pais = Pais.objects.get(pa_id = request.POST['pais'])
            frm.region = Region.objects.get(re_id = request.POST['region'])
            frm.comuna = Comuna.objects.get(com_id = request.POST['comuna'])
            frm.save()

            address = f"{ frm.co_address }, { frm.comuna.com_nombre }, { frm.region.re_nombre }, { frm.pais.pa_nombre }"
            lat_lng = getLatitudeLongitude(address)

            msg = ""
            if not lat_lng:
                msg = "La ubicación no pudo ser detectada, ingrese la latitud y longitud manualmente"
            else:
                frm.co_latitude = lat_lng['latitude']
                frm.co_longitude = lat_lng['longitude']
                frm.save()

            request.session['logo_company'] = f"media/{frm.co_logo.name}"

            # Agregar mensaje de éxito
            messages.success(request, 'Datos editados exitosamente!.')
        else:
            for field in form:
                for error in field.errors:
                    messages.error(request, f"{field.label}: {error}")
    else:
        form = CompanyForm(instance=object)

    return redirect('reinventa_app:configuracion')

@login_required
def controlPanel(request):
    
    excluded_results  = Reinventor.objects.filter(re_active='Y').filter(re_latitude__isnull=False, re_longitude__isnull=False)
    lstReinventrs = Reinventor.objects.filter(re_active='Y').exclude(re_latitude='').exclude(re_longitude='')

    try:
        objectCompany = Company.objects.all().first()
        request.session['lat_lng'] = {
            "co_latitude": objectCompany.co_latitude,
            "co_longitude": objectCompany.co_longitude,
        }
    except:
        pass

    data = {
        'lstReinventrs': lstReinventrs,
        'excluded_results': excluded_results,
        'cantReinventors': len(lstReinventrs)
    }
    return render(request, 'administrator/pages/maps.html', data)

@login_required
@is_data
def verReinventores(request):
    objectData = Reinventor.objects.filter(re_active = "Y")
    data = {
        'objectData': objectData,
    }
    return render(request, 'administrator/pages/ver_reinventores.html', data)

@login_required
def addUserReinventor(request, re_id):

    if request.method == 'POST':
        form = UserForm(request.POST)
        
        if form.is_valid():
            # Guardar los datos del formulario UserForm
            frm = form.save(commit=False)
            frm.is_staff = False
            frm.is_superuser = False
            frm.set_password(request.POST['password'])
            frm.save()

            ur = UserReinventor()
            ur.user = frm
            ur.ur_typeuser = 2
            ur.reinventor = Reinventor.objects.get(re_id = re_id)
            ur.save()

            messages.success(request, 'Usuario creado exitosamente!.')
            return redirect('reinventa_app:edit-user-reinventor', re_id=re_id, id=frm.id)
        
        else:
            for field in form:
                for error in field.errors:
                    messages.error(request, f"{field.label}: {error}")
    else:
        form = UserForm()
    data = {
        'action': 'crear',
        'form': form,
        're_id': re_id
    }
    return render(request, 'administrator/pages/form_user_reinventor.html', data)

@login_required
def editUserReinventor(request, re_id, id):
    object = get_object_or_404(User, id=id)

    if request.method == 'POST':
        form = UserForm(request.POST, instance=object)
        if form.is_valid():
            frm = form.save(commit=False)

            if len(request.POST['password']) == 0:
                password = object.username
                hashed_password = make_password(password)
                frm.password = hashed_password
                frm.save()
            else:

templates/reinventor/base.html
{% load static_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %} | {{ request.session.first_name|title }} {{ request.session.last_name|title }}</title>
    
    <!-- Bootstrap -->
    <link href="{% statics_tag 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% statics_tag 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% statics_tag 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="{% statics_tag 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css' %}"
        rel="stylesheet" />

    <!-- jQuery -->
    <script src="{% statics_tag 'vendors/jquery/dist/jquery.min.js' %}"></script>

    <link href="{% statics_tag 'vendors/jqueyconfirm/jquery-confirm.min.css' %}" rel="stylesheet">
    <script src="{% statics_tag 'vendors/jqueyconfirm/jquery-confirm.min.js' %}"></script>

    <!-- Custom Theme Style -->
    <link href="{% statics_tag 'build/css/custom.min.css' %}" rel="stylesheet">
    

    {% block static_up %}
    {% endblock %}
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col menu_fixed">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="#" class="site_title"><i class="fa fa-user"></i> <span>LokiLabs</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="images/img.jpg" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Bienvenido,</span>
                            <h2>{{ request.session.first_name|title }} {{ request.session.last_name|title }}</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li><a><i class="fa fa-home"></i> Inicio <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="#">Dashboard</a></li>
                                    </ul>
                                </li>
                                <li id="clientes" {% if request.session.item == 'clientes' %}class="active"{% else %}{% endif %}><a><i class="fa fa-building"></i> Reinventores <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" {% if request.session.item == 'clientes' %}style="display: block;"{% endif %}> 
                                        <li {% if request.session.sub_item == 'cliente' %}class="current-page"{% endif %}><a href="#">Ver Reinventores</a></li>
                                        <li {% if request.session.sub_item == 'report' %}class="current-page"{% endif %}><a href="#">Reporte</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->

                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout"
                            href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <nav class="nav navbar-nav">
                        <ul class=" navbar-right">
                            <li class="nav-item dropdown open" style="padding-left: 15px;">
                                <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true"
                                    id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                    <img src="images/img.jpg" alt="">{{ request.session.first_name|title }} {{ request.session.last_name|title }}
                                </a>
                                <div class="dropdown-menu dropdown-usermenu pull-right"
                                    aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="/page/" target="_blank"> Ver página oficial</a>
                                    <a class="dropdown-item" href="/admin/" target="_blank"> Ir a Admin Django</a>
                                    <a class="dropdown-item" href="{% url 'account_app:cerrar-sesion' %}"><i
                                            class="fa fa-sign-out pull-right"></i>
                                        Cerrar Sesión</a>
                                </div>
                            </li>

                            <!--<li role="presentation" class="nav-item dropdown open">
                                <a href="javascript:;" class="dropdown-toggle info-number" id="navbarDropdown1"
                                    data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="badge bg-green">6</span>
                                </a>
                                <ul class="dropdown-menu list-unstyled msg_list" role="menu"
                                    aria-labelledby="navbarDropdown1">
                                    <li class="nav-item">
                                        <a class="dropdown-item">
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were
                                                where...
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </li> -->


                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>{% block title_page %}Plain Page{% endblock %}</h3>
                        </div>

                        <div class="clearfix"></div>

                        <div class="row">
                            <div class="col-md-12 col-sm-12  ">
                                <div class="x_panel">
                                    <div class="x_title">
                                        <h2>{% block sub_title_page %}Plain Page{% endblock %}</h2>
                                        {% block menu_action %}Plain Page{% endblock %}
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="x_content">
                                        {% block content_page %}content_page{% endblock %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /page content -->

            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    HorusForce {{ my_date|date:"Y" }} - Desarrollado por <a href="#">[HF]</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    <!-- Bootstrap -->
    <script src="{% statics_tag 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% statics_tag 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% statics_tag 'vendors/nprogress/nprogress.js' %}"></script>
    <!-- jQuery custom content scroller -->
    <script src="{% statics_tag 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}">
    </script>

    <!-- Custom Theme Scripts -->
    <script src="{% statics_tag 'build/js/custom.js' %}"></script>

    {% block static_down %}
    {% endblock %}
</body>

</html>