applications/reinventor/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

from applications.reinventor.api.api import WithdrawalRequestUpdateAPIView, generatePdfAPIView
from applications.reinventor.views_error import error404
from . import views, views_ajax

app_name = 'reinventa_app'

urlpatterns = [
    path('dashboard/', views.controlPanel, name='panel-control'),
    path('listado-reinventores/', views.verReinventores, name='ver-reinventores'),
    path('crear-reinventor/', views.addReinventor, name='add-reinventor'),
    path('editar-reinventor/<int:re_id>', views.editReinventor, name='edit-reinventor'),
    path('borrar-reinventor/<int:re_id>', views.deleteReinventor, name='delete-reinventor'),
    path('logo-reinventor/<int:re_id>', views.addLogoReinventor, name='logo-reinventor'),

    path('configuracion', views.configurationCompany, name='configuracion'),

    path('crear-configuracion/', views.addConfiguration, name='crear-configuracion'),
    path('edit-configuracion/<int:co_id>', views.editConfiguration, name='edit-configuracion'),


    path('ver-request/', views.viewRequestAdmin, name='ver-request'),
    path('ver-user/', views.viewUserAdmin, name='ver-user'),
    path('add-user/', views.addUserAdmin, name='add-user'),
    path('edit-user/<int:id>', views.editUserAdmin, name='edit-user'),


    path('add-user-reinventor/<int:re_id>', views.addUserReinventor, name='add-user-reinventor'),
    path('edit-user-reinventor/<int:re_id>/<int:id>', views.editUserReinventor, name='edit-user-reinventor'),
    path('delete-user-reinventor/<int:re_id>/<int:id>', views.deleteUserReinventor, name='delete-user-reinventor'),


    path('list-request-reinventor/', views.listRequestReinventor, name='list-request-reinventor'),
    path('crear-request-reinventor/', views.addRequestReinventor, name='crear-request-reinventor'),
    path('edit-request-reinventor/<int:wrr_id>', views.editRequestReinventor, name='edit-request-reinventor'),
    path('ver-request-reinventor-adm/<int:wrr_id>', views.editRequestReinventor, name='edit-request-reinventor-adm'),


    path('add-observations/<int:wrr_id>', views.addObservations, name='add-observations'),
    path('edit-observations/<int:wrr_id>/<int:rt_id>', views.editObservations, name='edit-observations'),



    #ajax
    path('ajax/nueva-observacion/', views_ajax.new_observation, name='new_observation'),
    path('ajax/upload-file/', views_ajax.upload_file, name='upload_file'),
    path('ajax/download-excel-for-upload-reinventor/', views_ajax.download_excel_for_upload_reinventor, name='download_excel_for_upload_reinventor'),


    #api
    path('api/actualizar-estado/', WithdrawalRequestUpdateAPIView.as_view(), name='actualizar_estado'),
    path('api/generar-pdf/', generatePdfAPIView.as_view(), name='generar_pdf'),


    path('error404/', error404, name='error404'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reinventa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenBlacklistView
)

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from applications.account.api.api import Login, Logout
from applications.account.views import logout, logout_view

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version='v1',
        description="API documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@yourcompany.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[],
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('login/', Login.as_view(), name='login'),
    #path('logout/', Logout.as_view(), name='logout'),
    path('logout/', logout_view, name='logout'),

    path('', include('applications.account.urls')),
    path('', include('applications.reinventor.urls')),
    path('', include('applications.web.urls')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/blacklist/', TokenBlacklistView.as_view(), name='token_blacklist'),
]

applications/account/models.py
from django.contrib.auth.models import User
from django.db import models
from model_utils.models import TimeStampedModel


# Create your models here.

class Pais(TimeStampedModel):
    pa_id = models.AutoField("Key", primary_key=True)
    pa_nombre = models.CharField("Nombre país", max_length=255)
    pa_codigo = models.IntegerField("Código area país", unique=True)

    def __int__(self):
        return self.pa_id

    def __str__(self):
        return "{n}".format(n=self.pa_nombre.title())

    def save(self, *args, **kwargs):
        # print "save cto"
        super(Pais, self).save(*args, **kwargs)

    class Meta:
        db_table = 'conf_pais'
        ordering = ['pa_id']


class Region(TimeStampedModel):
    re_id = models.AutoField("Key", primary_key=True)
    re_nombre = models.CharField("Nombre región", max_length=255)
    pais = models.ForeignKey(Pais, verbose_name="País", blank=True, null=True, on_delete=models.PROTECT,
                             db_column="re_pais")
    re_numeroregion = models.CharField(
        "Sigla de región", blank=True, null=True, max_length=5)
    re_numero = models.IntegerField("Número de región", db_index=True)

    def __int__(self):
        return self.re_id

    def __str__(self):
        return "{n}".format(n=self.re_nombre.title())

    def save(self, *args, **kwargs):
        # print "save cto"
        super(Region, self).save(*args, **kwargs)

    class Meta:
        db_table = 'conf_region'
        ordering = ['re_id']


class Comuna(TimeStampedModel):
    com_id = models.AutoField("Key", primary_key=True)
    com_nombre = models.CharField("Nombre comuna", max_length=255)
    com_numero = models.IntegerField("Numero comuna", default=0)
    region = models.ForeignKey(Region, verbose_name="Región", blank=True, null=True, on_delete=models.PROTECT,
                               db_column="com_region")

    def __int__(self):
        return self.com_id

    def __str__(self):
        return "{n}".format(n=self.com_nombre.title())

    def save(self, *args, **kwargs):
        # print "save cto"
        super(Comuna, self).save(*args, **kwargs)

    class Meta:
        db_table = 'conf_comuna'
        ordering = ['com_id']


class Reinventor(TimeStampedModel): 

    OPTIONS = (
        ('Y', 'SI'),
        ('N', 'NO'),
    )

    re_id = models.AutoField("Key", primary_key=True)
    re_nameentity = models.CharField("Nombre empresa", max_length=255)
    # re_email = models.CharField("Correo empresa", max_length=255, unique=True)
    re_email = models.EmailField("Correo empresa", max_length=255, null=True, blank=True)
    re_namereinventor = models.CharField("Nombre completo persona a cargo", max_length=255)
    re_address = models.CharField("Dirección de la empresa", help_text="ej: calle siempre viva 1010", max_length=255)
    pais = models.ForeignKey(Pais, verbose_name="País",
                             db_column="re_pais_id", on_delete=models.PROTECT)
    region = models.ForeignKey(
        Region, verbose_name="Región", db_column="re_region_id", on_delete=models.PROTECT)
    comuna = models.ForeignKey(
        Comuna, verbose_name="Comuna", db_column="re_comuna_id", on_delete=models.PROTECT)
    
    re_latitude = models.CharField("Latitud", max_length=255, null=True, blank=True)
    re_longitude = models.CharField("Longitud", max_length=255, null=True, blank=True)
    re_logo = models.ImageField(
        "Logo Empresa", help_text=" Formatos .jpg|.png|.gif|.jpeg", upload_to='image/logo/', null=True, blank=True)
    
    re_active = models.CharField(
        "Activo", choices=OPTIONS, max_length=1, default="Y")
    

    def __int__(self):
        return self.re_id
    
    def __str__(self):
        return f"{self.re_id} - {self.re_nameentity}"
    
    def __create_address(self):
        return f"""{ self.re_address }, { self.comuna.com_nombre }, { self.region.re_nombre }, { self.pais.pa_nombre }"""

    re_createaddress = property(__create_address)

    def save(self, *args, **kwargs):
        super(Reinventor, self).save(*args, **kwargs)

    class Meta:
        db_table = "re_reinventor"
        ordering = ['re_id']


class UserReinventor(TimeStampedModel):
    OPTIONS = (
        ('Y', 'SI'),
        ('N', 'NO'),
    )

    TYPE_USER = (
        (0, ' [Seleccione] '),
        (1, 'ADMINISTRADOR REINVENTA'),
        (2, 'REINVENTOR'),
    )

    ur_id = models.AutoField("Key", primary_key=True)
    user = models.ForeignKey(User, verbose_name="User",
                             db_column="ur_user_id", on_delete=models.PROTECT)
    reinventor = models.ForeignKey(Reinventor, verbose_name="Reinventor",
                             db_column="ur_reinventor_id", on_delete=models.PROTECT)
    ur_typeuser = models.IntegerField(
        "Tipo de usuario", choices=TYPE_USER, default=0)
    ur_logo = models.ImageField(
        "Imagen usuario", help_text=" Formatos .jpg|.png|.gif|.jpeg", upload_to='image/logo/', default='../media/site/user_default.png', null=True, blank=True)
    ur_active = models.CharField(
        "Activo", choices=OPTIONS, max_length=1, default="Y")

    def __int__(self):
        return self.ur_id
    
    def __str__(self):
        return f"{ self.ur_id } - { self.user.username }"

    def save(self, *args, **kwargs):
        super(UserReinventor, self).save(*args, **kwargs)

    class Meta:
        db_table = "re_user_reinventor"
        ordering = ['ur_id']


class WithdrawalRequestReinventor(TimeStampedModel):
    OPTIONS = (
        ('Y', 'SI'),
        ('N', 'NO'),
    )

    ESTATE_REQUEST = (
        (0, ' [Seleccione] '),
        (1, 'REINVENTOR SOLICITA'),
        (2, 'VISTA POR REINVENTA'),
        (3, 'REINVENTA VA EN RUTA'),
        (4, 'RETIRADO POR REINVENTA'),
    )

    wrr_id = models.AutoField("Key", primary_key=True)
    user = models.ForeignKey(User, verbose_name="User",
                             db_column="ur_user_id", on_delete=models.PROTECT)
    reinventor = models.ForeignKey(Reinventor, verbose_name="Reinventor",
                             db_column="ur_reinventor_id", on_delete=models.PROTECT)
    wrr_date = models.CharField("Fecha de retiro", null=True, blank=True, max_length=30)
    wrr_quantityliters = models.FloatField("Litros de aceite", null=True, blank=True)
    wrr_estaterequest = models.IntegerField(
        "Estado de la solicitud", choices=ESTATE_REQUEST, default=1, null=True, blank=True)
    wrr_active = models.CharField(
        "Activo", max_length=1, choices=OPTIONS, default="Y")

    def __int__(self):
        return self.wrr_id
    
    def __str__(self):
        return f"{ self.wrr_id } - { self.user.username } - { self.reinventor.re_nameentity }"

    def save(self, *args, **kwargs):
        super(WithdrawalRequestReinventor, self).save(*args, **kwargs)

    class Meta:
        db_table = "re_withdrawal_request_reinventor"
        ordering = ['wrr_id']


class RequestTracking(TimeStampedModel):

    rt_id = models.AutoField("Key", primary_key=True)
    user = models.ForeignKey(User, verbose_name="User",
                             db_column="rt_user_id", on_delete=models.PROTECT)
    withdrawalRequestReinventor = models.ForeignKey(WithdrawalRequestReinventor, verbose_name="WithdrawalRequestReinventor",
                             db_column="rt_withdrawal_request_reinventor", on_delete=models.PROTECT)
    
    rt_estaterequest = models.CharField("Estado de la solicitud", max_length=50, blank=True, null=True)
    
    rt_observation = models.TextField("Observación", null=True, blank=True)

    def __int__(self):
        return self.rt_id
    
    def __str__(self):
        return f"{ self.rt_id } - { self.user.username } - { self.rt_estaterequest }"

    def save(self, *args, **kwargs):
        super(RequestTracking, self).save(*args, **kwargs)

    class Meta:
        db_table = "re_request_tracking"
        ordering = ['rt_id']

templates/administrator/pages/ver_reinventores.html
{% extends 'administrator/base.html' %}

{% load static_tags %}
{% load static %}

{% block title %}Listado Reinventores{% endblock %}

{% block static_up %}
<!-- Datatables -->

<link href="{% statics_tag 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}"
    rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">


{% endblock %}

{% block title_page %}{% endblock %}

{% block sub_title_page %}
Listado de Reinventores
{% endblock %}

{% block menu_action %}

{% endblock %}

{% block content_page %}
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Reinventores / Listado</h3>
        </div>
        <div class="title_right">
            <div class="col-md-5 col-sm-5 form-group pull-right top_search">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <button type="button" class="btn btn-info btn-sm" onclick="redirectToUrl('{% url 'reinventa_app:add-reinventor' %}')">Nuevo cliente <i class="fa fa-plus-circle"></i></button>
                    </li>
                    <li>
                        <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target=".bs-example-modal-lg">Carga masiva <i class="fa fa-plus-circle"></i></button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><i class="fa fa-list-ul"></i> <small>Listado de reinventores asociados</small></h2>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable-responsive" class="table table-striped table-bordered datatable" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Dirección</th>
                                <th>Latitud y Longitud</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in objectData %}
                            <tr>
                                <td>{{ object.re_id }}</td>
                                <td>{{ object.re_nameentity }}</td>
                                <td>{{ object.re_createaddress }}</td>
                                <td>
                                    {% if object.re_latitude and object.re_longitude %}
                                        {{ object.re_latitude }}, {{ object.re_longitude }}
                                    {% else %}
                                        Sin asignar
                                    {% endif %}
                                </td>
                                <td><button type="button" class="btn btn-info btn-sm" onclick="redirectToUrl('{% url 'reinventa_app:edit-reinventor' object.re_id %}')">Editar</button><button type="button"
                                        class="btn btn-danger btn-sm" onclick="deleteClient('{% url 'reinventa_app:delete-reinventor' object.re_id %}')">Eliminar</button></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Carga masiva reinventores</h4>
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <h4>Cargar excel (.xls, .xlsx)</h4>
                <input type="file" name="file-excel" id="file-excel" class="form-control">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="download_file_excel()">Descargar plantilla</button>
                <button class="btn btn-primary" type="button" onclick="upload_excel()"> Subir Excel 
                    <span class="spinner-border spinner-border-sm" id="loading-button" role="status" aria-hidden="true"></span>
                    <span class="sr-only">Loading...</span>
                </button>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function() {
        var table = $('#datatable-responsive').DataTable( {
            responsive: true
        });

        $("#loading-button").hide()
    });

    const redirectToUrl = (url) => {
        location.href = url;
    }

    const deleteClient = (url) => {
        $.confirm({
            title: 'Confirmación',
            content: 'Esta eguro de eliminar al reinventor?, para eliminar haga clic confirmar, de lo contrario cancelar',
            buttons: {
                confirmar: function () {
                    location.href = url;
                },
                cancelar: function () {
                    $.alert('Operación cancelada');
                },
            }
        });
    }


    const upload_excel = () => {
        const fileInput = document.getElementById('file-excel');
        const file = fileInput.files[0];

        // Verificar si se seleccionó un archivo
        if (!file) {
            $.alert({
                title: 'Alerta!',
                content: 'Debes seleccionar un archivo para continuar.',
            });
            return;
        }

        const allowedExtensions = [".xls", ".xlsx"];
        const extension = file.name.substring(file.name.lastIndexOf(".")).toLowerCase();
        let itIsAllowed = false;

        for (let i = 0; i < allowedExtensions.length; i++) {
            if (allowedExtensions[i] === extension) {
                itIsAllowed = true;
                break;
            }
        }

        if (itIsAllowed) {
            // Archivo con extensión permitida, proceder con la conversión a base64
            const reader = new FileReader();

            reader.onload = function () {
                const base64String = reader.result.split(',')[1];
                // Enviar el archivo en base64 a un endpoint con fetch
                enviarArchivo(base64String);
            };

            reader.readAsDataURL(file);
        } else {
            $.alert({
                title: 'Alerta!',
                content: 'El archivo seleccionado no tiene una extensión válida.',
            });
            return;
        }
    };

    const enviarArchivo = (base64String) => {
        // Aquí debes proporcionar la URL de tu endpoint

        $("#loading-button").show()

        $.ajax({
            url: '{% url 'reinventa_app:upload_file' %}',
            type: 'POST',
            dataType: 'json',
            data: {
                'file_data': base64String,
            },
            success: function(data) {

                if(data.response.details){
                    base64ToExcel(data.response.details, 'no_ingresados.xlsx');
                }

                $.confirm({
                    title: 'Confirmación',
                    content: `La carga fue realizada con éxito`,
                    buttons: {
                        aceptar: function () {
                            location.reload();
                        }
                    }
                });
            },
            error: function(error) {
                console.error('Error:', error);
            }
        });
    };

    const download_file_excel = () => {
        $.ajax({
            url: '{% url 'reinventa_app:download_excel_for_upload_reinventor' %}',
            type: 'POST',
            dataType: 'json',
            success: function(data) {
                if (data && data.response.message) {
                    // Llamada a la función para convertir y descargar el archivo Excel
                    base64ToExcel(data.response.message, 'archivo_excel.xlsx');
                } else {
                    console.error('Error: No se recibió el base64 del servidor.');
                }
            },
            error: function(error) {
                console.error('Error:', error);
            }
        });
    };

    // Función para convertir la cadena base64 a Excel y descargar el archivo
    function base64ToExcel(base64Data, filename) {
        // Decodificar la cadena base64
        const byteCharacters = atob(base64Data);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);

        // Crear un Blob con los datos decodificados
        const blob = new Blob([byteArray], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });

        // Crear un enlace para descargar el archivo
        const link = document.createElement('a');
        link.href = window.URL.createObjectURL(blob);
        link.download = filename;

        // Simular un clic en el enlace para iniciar la descarga
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
    
</script>

{% endblock %}

{% block static_down %}
<!-- Datatables -->
<script src="{% statics_tag 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
<script src="{% statics_tag 'vendors/jszip/dist/jszip.min.js' %}"></script>
<script src="{% statics_tag 'vendors/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% statics_tag 'vendors/pdfmake/build/vfs_fonts.js' %}"></script>


{% endblock %}

templates/administrator/pages/ver_request.html
{% extends 'administrator/base.html' %}

{% load static_tags %}
{% load static %}

{% block title %}Listado Reinventores{% endblock %}

{% block static_up %}
<!-- Datatables -->

<link href="{% statics_tag 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}"
    rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
<link href="{% statics_tag 'vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">


{% endblock %}

{% block title_page %}{% endblock %}

{% block sub_title_page %}
Listado de Solicitudes
{% endblock %}

{% block menu_action %}

{% endblock %}

{% block content_page %}

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Reinventa / Solicitudes</h3>
        </div>
        <div class="title_right">
            <div class="col-md-5 col-sm-5 form-group pull-right top_search">
                <div class="input-group">

                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><i class="fa fa-list-ul"></i> <small>Listado de solicitudes</small></h2>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable-responsive" class="table table-striped table-bordered datatable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Usuario</th>
                                <th>Reinventor</th>
                                <th>Fecha solicitud de retiro</th>
                                <th>Listros de aceite</th>
                                <th>Estado de la solicitud</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in objectData %}
                            <tr>
                                <td>{{ object.wrr_id }}</td>
                                <td>{{ object.user.first_name | upper }} {{ object.user.last_name | upper }}</td>
                                <td>{{ object.reinventor.re_nameentity | upper }}</td>
                                <td>{{ object.wrr_date }}</td>
                                <td>{{ object.wrr_quantityliters }}</td>
                                <td>{{ object.get_wrr_estaterequest_display }}</td>
                                <td>
                                    <button type="button" class="btn btn-info btn-sm" onclick="redirectToUrl('{% url 'reinventa_app:edit-request-reinventor-adm' object.wrr_id %}')">Ver Solicitud  <i class="fa fa-eye"></i></button>
                                    <button type="button" class="btn btn-danger btn-sm" onclick="">PDF <i class="fa fa-file-pdf-o"></i></button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function() {
        var table = $('#datatable-responsive').DataTable( {
            responsive: true
        } );
    } );

    const redirectToUrl = (url) => {
        location.href = url;
    }

    const deleteClient = (url) => {
        $.confirm({
            title: 'Confirmación',
            content: 'Esta eguro de eliminar al reinventor?, para eliminar haga clic confirmar, de lo contrario cancelar',
            buttons: {
                confirmar: function () {
                    location.href = url;
                },
                cancelar: function () {
                    $.alert('Operación cancelada');
                },
            }
        });
    }
</script>

{% endblock %}

{% block static_down %}
<!-- Datatables -->
<script src="{% statics_tag 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
<script src="{% statics_tag 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
<script src="{% statics_tag 'vendors/jszip/dist/jszip.min.js' %}"></script>
<script src="{% statics_tag 'vendors/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% statics_tag 'vendors/pdfmake/build/vfs_fonts.js' %}"></script>


{% endblock %}