applications/reinventor/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

from applications.reinventor.api.api import WithdrawalRequestUpdateAPIView, generatePdfAPIView
from applications.reinventor.views_error import error404
from . import views, views_ajax

app_name = 'reinventa_app'

urlpatterns = [
    path('dashboard/', views.controlPanel, name='panel-control'),
    path('listado-reinventores/', views.verReinventores, name='ver-reinventores'),
    path('crear-reinventor/', views.addReinventor, name='add-reinventor'),
    path('editar-reinventor/<int:re_id>', views.editReinventor, name='edit-reinventor'),
    path('borrar-reinventor/<int:re_id>', views.deleteReinventor, name='delete-reinventor'),
    path('logo-reinventor/<int:re_id>', views.addLogoReinventor, name='logo-reinventor'),

    path('configuracion', views.configurationCompany, name='configuracion'),

    path('crear-configuracion/', views.addConfiguration, name='crear-configuracion'),
    path('edit-configuracion/<int:co_id>', views.editConfiguration, name='edit-configuracion'),


    path('ver-request/', views.viewRequestAdmin, name='ver-request'),
    path('ver-user/', views.viewUserAdmin, name='ver-user'),
    path('add-user/', views.addUserAdmin, name='add-user'),
    path('edit-user/<int:id>', views.editUserAdmin, name='edit-user'),


    path('add-user-reinventor/<int:re_id>', views.addUserReinventor, name='add-user-reinventor'),
    path('edit-user-reinventor/<int:re_id>/<int:id>', views.editUserReinventor, name='edit-user-reinventor'),
    path('delete-user-reinventor/<int:re_id>/<int:id>', views.deleteUserReinventor, name='delete-user-reinventor'),


    path('list-request-reinventor/', views.listRequestReinventor, name='list-request-reinventor'),
    path('crear-request-reinventor/', views.addRequestReinventor, name='crear-request-reinventor'),
    path('edit-request-reinventor/<int:wrr_id>', views.editRequestReinventor, name='edit-request-reinventor'),
    path('ver-request-reinventor-adm/<int:wrr_id>', views.editRequestReinventor, name='edit-request-reinventor-adm'),


    path('add-observations/<int:wrr_id>', views.addObservations, name='add-observations'),
    path('edit-observations/<int:wrr_id>/<int:rt_id>', views.editObservations, name='edit-observations'),



    #ajax
    path('ajax/nueva-observacion/', views_ajax.new_observation, name='new_observation'),
    path('ajax/upload-file/', views_ajax.upload_file, name='upload_file'),
    path('ajax/download-excel-for-upload-reinventor/', views_ajax.download_excel_for_upload_reinventor, name='download_excel_for_upload_reinventor'),


    #api
    path('api/actualizar-estado/', WithdrawalRequestUpdateAPIView.as_view(), name='actualizar_estado'),
    path('api/generar-pdf/', generatePdfAPIView.as_view(), name='generar_pdf'),


    path('error404/', error404, name='error404'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reinventa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenBlacklistView
)

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from applications.account.api.api import Login, Logout
from applications.account.views import logout, logout_view

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version='v1',
        description="API documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@yourcompany.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[],
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('login/', Login.as_view(), name='login'),
    #path('logout/', Logout.as_view(), name='logout'),
    path('logout/', logout_view, name='logout'),

    path('', include('applications.account.urls')),
    path('', include('applications.reinventor.urls')),
    path('', include('applications.web.urls')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/blacklist/', TokenBlacklistView.as_view(), name='token_blacklist'),
]

templates/administrator/base.html
{% load static_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %} | {{ request.session.first_name|title }} {{ request.session.last_name|title }}</title>
    
    <!-- Bootstrap -->
    <link href="{% statics_tag 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% statics_tag 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% statics_tag 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="{% statics_tag 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css' %}"
        rel="stylesheet" />

    <!-- jQuery -->
    <script src="{% statics_tag 'vendors/jquery/dist/jquery.min.js' %}"></script>

    <link href="{% statics_tag 'vendors/jqueyconfirm/jquery-confirm.min.css' %}" rel="stylesheet">
    <script src="{% statics_tag 'vendors/jqueyconfirm/jquery-confirm.min.js' %}"></script>

    <!-- Custom Theme Style -->
    <link href="{% statics_tag 'build/css/custom.min.css' %}" rel="stylesheet">
    <link href="{% statics_tag 'build/css/override.css' %}" rel="stylesheet">
    <script src="{% statics_tag_all 'js/axios.min.js' %}"></script>
    
    <style>
        .title_left{
            padding-left: 10px;
        }

        .select2 .select2-container .select2-container--default .select2-container--focus{
            width: 358px;
        }
    </style>
    {% block static_up %}
    {% endblock %}
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col menu_fixed">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title div_center" style="border: 0;">
                        <div class="div_center_son">
                            <a href="javascript:void()" class="am-logo">
                                <img src="{{ request.session.logo_company }}" width="450" class="img-fluid img-thumbnail img-thumbnail-logo" alt="">
                            </a>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix" style="margin-top: 20%;">
                        <div class="profile_pic">
                            <img src="{{ request.session.logo_user }}" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Bienvenido, </span>
                            <h2>{{ request.session.first_name|title }} {{ request.session.last_name|title }}</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            {% if request.session.objectCompany.ur_typeuser == 1 %}
                            <ul class="nav side-menu">
                                <li><a><i class="fa fa-home"></i> Inicio <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="{% url 'reinventa_app:panel-control' %}">Dashboard</a></li>
                                    </ul>
                                </li>
                                <li id="reinventa" {% if request.session.item == 'reinventa' %}class="active"{% else %}{% endif %}><a><i class="fa fa-cube"></i> Reinventa <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" {% if request.session.item == 'reinventa' %}style="display: block;"{% endif %}> 
                                        <li {% if request.session.sub_item == 'configuracion' %}class="current-page"{% endif %}><a href="{% url 'reinventa_app:configuracion' %}">Configuración</a></li>
                                        <li {% if request.session.sub_item == 'solicitudes' %}class="current-page"{% endif %}><a href="{% url 'reinventa_app:ver-request' %}">Solicitudes</a></li>
                                        <li {% if request.session.sub_item == 'usuarios' %}class="current-page"{% endif %}><a href="{% url 'reinventa_app:ver-user' %}">Usuarios</a></li>
                                    </ul>
                                </li>
                                <li id="clientes" {% if request.session.item == 'reinventores' %}class="active"{% else %}{% endif %}><a><i class="fa fa-building"></i> Reinventores <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" {% if request.session.item == 'reinventores' %}style="display: block;"{% endif %}> 
                                        <li {% if request.session.sub_item == 'ver_reinventores' %}class="current-page"{% endif %}><a href="{% url 'reinventa_app:ver-reinventores' %}">Ver Reinventores</a></li>
                                    </ul>
                                </li>
                            </ul>
                            {% else %}
                            <ul class="nav side-menu">
                                <li><a><i class="fa fa-home"></i> Inicio <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="{% url 'reinventa_app:panel-control' %}">Dashboard</a></li>
                                    </ul>
                                </li>
                                <li id="clientes" {% if request.session.item == 'reinventores' %}class="active"{% else %}{% endif %}><a><i class="fa fa-building"></i> Reinventores <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" {% if request.session.item == 'reinventores' %}style="display: block;"{% endif %}> 
                                        <li {% if request.session.sub_item == 'list_request_reinventor' %}class="current-page"{% endif %}><a href="{% url 'reinventa_app:list-request-reinventor' %}">Solicitudes</a></li>
                                    </ul>
                                </li>
                            </ul>
                            {% endif %}
                        </div>
                    </div>
                    <!-- /sidebar menu -->

                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout"
                            href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <nav class="nav navbar-nav">
                        <ul class=" navbar-right">
                            <li class="nav-item dropdown open" style="padding-left: 15px;">
                                <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true"
                                    id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                    <img src="{{ request.session.logo_user }}" alt="">{{ request.session.first_name|title }} {{ request.session.last_name|title }}
                                </a>
                                <div class="dropdown-menu dropdown-usermenu pull-right"
                                    aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="/page/" target="_blank"> Ver página oficial</a>
                                    {% if request.session.objectCompany.admin %}
                                    <a class="dropdown-item" href="/admin/" target="_blank"> Ir a Admin Django</a>
                                    {% endif %}
                                    <a class="dropdown-item" href="{% url 'logout' %}"><i
                                            class="fa fa-sign-out pull-right"></i>
                                        Cerrar Sesión</a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    {% block content_page %}content_page{% endblock %}
                </div>
            </div>
            <!-- /page content -->

            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    HorusForce {{ my_date|date:"Y" }} - Desarrollado por <a href="#">[HF]</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    <!-- Bootstrap -->
    <script src="{% statics_tag 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% statics_tag 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% statics_tag 'vendors/nprogress/nprogress.js' %}"></script>
    <!-- jQuery custom content scroller -->
    <script src="{% statics_tag 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}">
    </script>

    <!-- Custom Theme Scripts -->
    <script src="{% statics_tag 'build/js/custom.js' %}"></script>

    {% block static_down %}
    {% endblock %}
</body>

</html>

templates/administrator/login.html
{% load static_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>REINVENTA</title>

    <!-- Bootstrap -->
    <link href="{% statics_tag 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% statics_tag 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

    <script src="{% statics_tag 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% statics_tag 'vendors/jquery/dist/jquery.min.js' %}"></script>




    <link href="{% statics_tag 'build/css/style-login.css' %}" rel="stylesheet">

</head>

<body>
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Ingresar</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa-solid fa-user"></i></span>
                            </div>
                            {{ form.username}}
                            
                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{ form.password}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Ingresar" class="btn float-right login_btn">
                        </div>
                    </form>
                    {% if error %}
                        <p>{{ error }}</p>
                        <div class="clearfix"></div>
                    {% endif %}
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center">
                        <a href="#">Olvidaste tu contraseña?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>